FROM python:3.7

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "main.py", "-c", "BTC_BTS", "-p", "60"]
