version: '3'
services:
    app:
        container_name: app_poloniex
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-app
        depends_on:
            - db
    db:
        container_name: db_poloniex
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-db
        ports:
            - "33060:3306"
        volumes:
            - db-init:/var/lib/mysql
    web:
        container_name: web_poloniex
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "5004:5004"
        depends_on:
            - app
volumes:
    db-init:
