FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /usr/src/app/web
COPY . /usr/src/app/web

EXPOSE 7000

RUN apk add gcc
RUN apk add --no-cache libressl-dev musl-dev libffi-dev
RUN pip install --no-cache-dir cryptography

RUN pip install --upgrade pip
RUN pip install -r web/requirements.txt

ENTRYPOINT ["python", "-m", "web.app"]
