version: '3'
services:

    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile-app
        links:
            - db
        depends_on:
            - db
    db:
        container_name: db
        image: mysql:5.7
        environment:
            - MYSQL_USER=jv
            - MYSQL_DB=api_poloniex
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
    web:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "5004:5004"
        depends_on:
            - app
volumes:
    db_init:
