FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=jv
ENV MYSQL_PASSWORD=sci@2017
ENV MYSQL_DATABASE=poloniex

RUN apt-get update

WORKDIR /usr/src/db

COPY db/init.sql /docker-entrypoint-initdb.d/init.sql

VOLUME /var/lib/mysql
