version: '3'
services:

    db:
        container_name: db
        image: mysql:5.7
        restart: always
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_DATABASE=poloniex
            - MYSQL_USER=jv
            - MYSQL_PASSWORD=sci@2017
            - MYSQL_ROOT_PASSWORD=root
    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-app
        links:
            - db
        depends_on:
            - db
    web:
        container_name: web
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "7000:7000"
        depends_on:
            - app
volumes:
    db_init:
